site_name: 2D Materials Project
site_url: https://example.com/
theme: 
 name: "material"
plugins:
 - mkdocstrings
nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - Howto: howto.md
  - Reference: reference.md
  - Topic guides: Topic_guides.md
