site_name: 2D Materials Project
site_url: https://example.com/
theme: readthedocs
 
plugins:
 - mkdocstrings
nav:
  - Home: index.md
  - Dataflow Diagram: DataFlowDiagram.md
  - Pseudocode: Pseudocode.md
  - Tests: Tests.md
  - Workflow: Workflow.md
